# docker-compose.yml

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=wowbagger
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
